apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: BCRYPT_SALT_ROUNDS
              valueFrom:
                configMapKeyRef:
                  key: BCRYPT_SALT_ROUNDS
                  name: backend-env
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: DB_DATABASE
                  name: backend-env
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: DB_HOST
                  name: backend-env
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DB_PASSWORD
                  name: backend-env
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: DB_PORT
                  name: backend-env
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  key: DB_USER
                  name: backend-env
            - name: JWT_EXPIRATION
              valueFrom:
                configMapKeyRef:
                  key: JWT_EXPIRATION
                  name: backend-env
            - name: JWT_QR_SECRET
              valueFrom:
                configMapKeyRef:
                  key: JWT_QR_SECRET
                  name: backend-env
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  key: JWT_SECRET
                  name: backend-env
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: PORT
                  name: backend-env
            - name: systemGENERATE_SOURCEMAP
              valueFrom:
                configMapKeyRef:
                  key: systemGENERATE_SOURCEMAP
                  name: backend-env
          image: backend
          name: backend-ca2e
          ports:
            - containerPort: 3001
              protocol: TCP
      restartPolicy: Always
