version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_ca2e
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: CA2E
    ports:
      - "5433:5432"
    volumes:
      - ca2e_pgdata:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - ca2e_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./mon_backend
      dockerfile: Dockerfile
    container_name: backend_ca2e
    restart: unless-stopped
    env_file:
      - ./mon_backend/.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ca2e_network
    ports:
      - "3001:3001"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  frontend:
    build:
      context: ./mon_frontend_react
      dockerfile: Dockerfile
    container_name: frontend_ca2e
    restart: unless-stopped
    volumes:
      - ./mon_frontend_react/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - ca2e_network

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer_ca2e
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    networks:
      - ca2e_network

volumes:
  ca2e_pgdata:
  portainer_data:

networks:
  ca2e_network:
    driver: bridge
